### ISSUE TITLE
An error occurred when choosing the latest package available on the server.

### ISSUE THREAD

**Issue by el-musleh** [worproject/WoR-Translations#32]
Hi, 
Regarding "WoR_Release_2.0.0-alpha.3"
I know this is not the right place but this is the only place I can reach you since ["bug tracker page." ](https://www.worproject.ml/bugtracker/my_view_page.php) is not functioning, I tried to create 3 different accounts and I got this message 
"Congratulations, you have registered successfully! You are now being sent a confirmation e-mail to verify your e-mail address. Visiting the link sent to you in this e-mail will activate your account." 
but none of the accounts received any confirmation email. 

I want to ask about the "Select the drivers" under the "Select drivers" tap. I got an error "An error occurred! please check the logs." in the log file "[error] The underlying connection was closed: An unexpected error occurred on a receive."
[Photo] https://drive.google.com/file/d/1xlzNpnTBw3nBxb6NuntlcKK6-VGbz4Qw/view?usp=sharing
[Log File] https://drive.google.com/file/d/1vRJwdimcWeqMeWO8g5C63n-owB7oF02C/view?usp=sharing

Can you help what to do? or what is wrong? If I want to use a package stored on your computer from where should I bring it? and is it important since the windows update can install the drivers automatically!

**Comment by worproject** [comment]
Please check the SPAM folder in your e-mail. The confirmation message may be there.

It seems to be a network issue on your side.
I see you're using an insider build of Windows, which may be the cause of this.

You can find the required packages here:
https://github.com/worproject/RPi-Windows-Drivers/releases
https://github.com/pftf/RPi4/releases
