### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by dlswe** [worproject/WoR-Translations#33]
My first attempt at a translation into Swedish
[[WoR lang file]sv_SE.txt](https://github.com/worproject/WoR-Translations/files/4951928/WoR.lang.file.sv_SE.txt)

**Comment by dlswe** [comment]
[[WoR lang file]sv_SE.txt](https://github.com/worproject/WoR-Translations/files/4951963/WoR.lang.file.sv_SE.txt)
Now with more proof-reading.

**Comment by dlswe** [comment]
Further proof-read.
[[WoR lang file]sv_SE.txt](https://github.com/worproject/WoR-Translations/files/4951999/WoR.lang.file.sv_SE.txt)

**Comment by worproject** [comment]
4d8d49645e2318b96c30bae18ac587b2df61fb98
