### ISSUE TITLE
Full Dutch translation FInished

### ISSUE THREAD

**Issue by finnie2006** [worproject/WoR-Translations#35]
Hello i created a full dutch translation and its finished

Edit : i can't post files here with the .ing format So you only need to give it the right file extension

[nl-NL.lng.txt](https://github.com/worproject/WoR-Translations/files/4977514/nl-NL.lng.txt)

**Comment by finnie2006** [comment]
is it good

**Comment by worproject** [comment]
1c7e7385e8ba21624c9feb71039f75deba829bd0

**Comment by finnie2006** [comment]
i will edit the 2 last strings

**Comment by finnie2006** [comment]
[nl-NL.lng.txt](https://github.com/worproject/WoR-Translations/files/4982358/nl-NL.lng.txt)

translated the mounting and unmounting string
