### ISSUE TITLE
Dutch Translation

### ISSUE THREAD

**Issue by finnie2006** [worproject/WoR-Translations#36]
Hello i maded the dutch translation but in the readme it sas outdated but its bases from the most recent version

**Comment by worproject** [comment]
These strings are not translated:
```
StatusBar.MountingISO=Mounting the ISO image...
StatusBar.UnmountingISO=Unmounting the ISO image...
```

**Comment by finnie2006** [comment]
[nl-NL.lng.txt](https://github.com/worproject/WoR-Translations/files/4982363/nl-NL.lng.txt)

translated the mounting and unmounting string

**Comment by finnie2006** [comment]
I will update the Dutch language every update

**Comment by worproject** [comment]
Thanks. I've merged the changes internally.

As a side note, please keep the `{n}{n}` blocks as they are in the future (without any additional spaces or alterations). In your translation file they were replaced with `{N} {n}`, in which case they won't display properly.

The translation should match the English one as much as possible (in terms of punctuation, word capitalization etc.)
